export default {
	MSG001: 'User does not exist',
	MSG002: 'Username and password do not match',
	MSG003: 'Your account is locked',
	MSG004: 'Full name is not valid',
	MSG005: 'Username is not valid use number also',
	MSG006: 'Password is not strong!Enter a password Like Test@123',
	MSG007: 'Please enter a valid mobile number',
	MSG008: 'City name should be valid',
	MSG009: 'Account partnership % is not valid',
	MSG010: 'Amount is not valid',
	MSG011: 'Master Password code is not valid',
	MSG012: 'User type is not valid',
	MSG013: 'Transaction sender/receiver is not valid user',
	MSG014: 'Invalid transaction',
	MSG015: 'Insufficient amount',
	MSG016: 'Current password did not matched',
	MSG017: 'Exposure amount is not valid',
	MSG018: 'Change amount is not valid',
	MSG019: 'Settle amount is not valid',

MSG020: 'Username already in use',
MSG021: 'Moblie already in use',
MSG022: 'Email already in use',
MSG023: 'Otp not found',
MSG024: 'Password is incorrect',
NOT_FOUND: 'Oops! No data found',
SOMETHING_WRONG: 'Oops! Something went wrong',
	
};